[project]
name = "ai-negotiator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-core>=0.3.72",
    "langchain-groq>=0.3.6",
    "langgraph>=0.5.4",
]
